language: node_js

node_js:
  "8"

cache:
  yarn: true
  directories:
    - node_modules
    - dist

script:
  - yarn lint
  - yarn test
  - NODE_ENV=production yarn build

before_deploy: "ls -al dist"

deploy:
  provider: npm
  email: opensource@ekino.com
  skip_cleanup: true
  api_key:
    secure: $API_KEY
  on:
    tags: true
    repo: ekino/webpack-plugin-assets-to-map
